name: Default CI

on:
  push:
    branches:
      - master
      - feature/17-ci-github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: make start
    - run: make test
